<?php

/**
 * @file
 * OpenEuropa module.
 */

declare(strict_types = 1);

use Drupal\poc_nextcloud\Service\UserSync;
use Drupal\user\UserInterface;

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function poc_nextcloud_user_update(UserInterface $user): void {
  UserSync::syncUserIfNextcloudAvailable($user);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function poc_nextcloud_user_insert(UserInterface $user): void {
  UserSync::syncUserIfNextcloudAvailable($user);
}
